const places = [
  {
    name: 'THE POPUP!',
    address: 'Dvorecké nám. 406/5, 147 00 Praha 4-Podolí',
    coordinates: '50.0464865,14.4141612,18z',
    opening_hours:
      'ÚT / ČT Individuálně dle dohody  PO / ST / PÁ 14:00 - 20:00 SO / NE 10:00 - 18:30 ',
    url: 'https://www.thepopup.cz/',
    img: './img/The Pop Up!',
  },
  {
    name: 'Neviditelná večeře',
    address:
      'Novoměstská radnice 2. patro Karlovo nám. 1/23 - vstup z Vodičkovy ulice 120 00 Praha 2',
    coordinates: '50.078158,14.42119,14z',
    opening_hours:
      'Po - Pá: 12:00 - 20:00 (Poslední návštěvníci v 19:00) So - Ne a svátky: 10:00 - 20:00 (Poslední návštěvníci v 19:00)',
    url: 'https://neviditelna.cz/neviditelna-vecere',
    img: './img/Neviditelna vecere',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Prague Boats - vyhlídková plavba',
    address: 'Dvořákovo nábř., 110 00 Josefov, Česko',
    coordinates: '50.091838,14.416337,15z',
    opening_hours:
      'kancelář na nástupišti číslo 3 je otevřena denně od 9.00 do 22.00',
    url: 'https://www.prague-boats.cz/cs/plavby-po-vltave',
    img: '',
  },

  {
    name: 'Půjčovna lodiček a šlapadel Slovanka',
    address: 'Slovanský ostrov, Praha 1, 110 00',
    coordinates: '50.0793101,14.4121909,15z',
    opening_hours: 'OTEVŘENO každý den od 11:00-22:50 za pěkného počasí.',
    url: 'https://www.slovanka.net/index.php',
    img: '',
  },
  {
    name: 'Motokáry Radotín',
    address: 'Výpadová 1335, Praha 5 Radotín',
    coordinates: '49.9869742,14.3711757,17z',
    opening_hours: 'Pondělí až neděle, 11:00 - 24:00',
    url: 'https://www.kart-centrum.cz/',
    img: '',
  },
  {
    name: 'Letní kino Sunset cinema',
    address:
      'Střecha obchodního centra Arkády Pankrác, Na Pankráci 86, 140 00 Praha 4-Nusle',
    coordinates: '50.0509039,14.4360898,17z',
    opening_hours: '',
    url: 'http://sunsetcinema.cz/cz',
    img: '',
  },
  {
    name: 'Ladronka - in-line',
    address: 'Tomanova 1028/1, 169 00 Praha 6-Břevnov',
    coordinates: '50.0787136,14.3541518,17z',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'JumpArena',
    address: 'Ringhofferova 1,155 00 Zličín,Praha 5',
    coordinates: '50.055025,14.293349,16z',
    opening_hours:
      'Pondělí - pátek 10:00 - 20:00,Sobota a neděle 09:00 - 20:00',
    url: 'https://zlicin.jumppark.cz/',
    img: '',
  },
];

const nature = [
  {
    name: 'Petřínské sady',
    address: 'Petřínské sady 118 00, 118 00 Praha 1-Malá Strana',
    coordinates: '50.0822666,14.4004938,17z',
    opening_hours: 'Otevřeno 24 hodin',
    url: '',
    img: '',
  },
  {
    name: 'Grébovka',
    address: 'Havlíčkovy sady, 120 00 Praha 2-Vinohrady',
    coordinates: '50.0694696,14.4359799,16z',
    opening_hours: 'Otevřeno ⋅ Zavírá v 22',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
  {
    name: 'Laser game',
    address: '',
    coordinates: '',
    opening_hours: '',
    url: '',
    img: '',
  },
];
